apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: default
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: MTA5OTI3MjA3MjkzOS00bXNqa20zN3RvdGM2aDNvNTlicDlqdDRwaXQ5OG1oMC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQ==
  GOOGLE_CLIENT_SECRET: R09DU1BYLVdiSnktUF81QWVSWUhKUFZrb2FGZEUxSm1nRWY=
  SESSION_SECRET: amFraXNfaW5ueV9rbHVjeg==