apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
  labels:
    app: quiz-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
        - name: quiz-service
          image: quiz-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: quiz-config
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: quiz-secrets
                  key: JWT_SECRET
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: quiz-config
                  key: AUTH_SERVICE_URL
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
