apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  MONGO_URI: "mongodb://mongo.default.svc.cluster.local:27017/authdb"
  AUTH_SERVICE_URL: "http://auth-service.default.svc.cluster.local:5003/api/auth"
